import type { BlogPost, City, CoachCategory, CoachProfile, FaqItem } from "@/types/domain";

export const coachCategories: CoachCategory[] = [
  {
    id: "personal",
    slug: "personal",
    name: "Coaching personal",
    shortDescription: "Habitos, claridad, autoestima y objetivos personales.",
    icon: "compass",
  },
  {
    id: "bienestar",
    slug: "bienestar",
    name: "Coaching de bienestar",
    shortDescription: "Rutinas, energia, bienestar emocional y cambios sostenibles.",
    icon: "sparkles",
  },
  {
    id: "emocional",
    slug: "emocional",
    name: "Coaching emocional",
    shortDescription: "Gestion emocional, regulacion y procesos de cambio con acompanamiento.",
    icon: "heart",
  },
  {
    id: "confianza-en-si-mismo",
    slug: "confianza-en-si-mismo",
    name: "Coaching de confianza en si mismo",
    shortDescription: "Seguridad personal, autoimagen y capacidad de accion en momentos clave.",
    icon: "shield",
  },
  {
    id: "carrera",
    slug: "carrera",
    name: "Coaching de carrera",
    shortDescription: "Cambio profesional, entrevistas y transicion laboral.",
    icon: "briefcase",
  },
  {
    id: "liderazgo",
    slug: "liderazgo",
    name: "Coaching de liderazgo",
    shortDescription: "Comunicacion, equipos y rendimiento profesional.",
    icon: "users",
  },
  {
    id: "ejecutivo",
    slug: "ejecutivo",
    name: "Coaching ejecutivo",
    shortDescription: "Direccion, estrategia y toma de decisiones.",
    icon: "building",
  },
  {
    id: "pareja",
    slug: "pareja",
    name: "Coaching de pareja",
    shortDescription: "Comunicacion, acuerdos y objetivos compartidos.",
    icon: "heart",
  },
  {
    id: "bioemocional",
    slug: "bioemocional",
    name: "Coaching bioemocional",
    shortDescription: "Gestion emocional y procesos de cambio profundos.",
    icon: "sparkles",
  },
  {
    id: "mujeres-emprendedoras",
    slug: "mujeres-emprendedoras",
    name: "Coaching para mujeres emprendedoras",
    shortDescription: "Foco, claridad comercial y sosten del crecimiento para proyectos personales.",
    icon: "rocket",
  },
];

export const cities: City[] = [
  { id: "madrid", slug: "madrid", name: "Madrid", country: "Espana" },
  { id: "barcelona", slug: "barcelona", name: "Barcelona", country: "Espana" },
  { id: "valencia", slug: "valencia", name: "Valencia", country: "Espana" },
  { id: "sevilla", slug: "sevilla", name: "Sevilla", country: "Espana" },
  { id: "bilbao", slug: "bilbao", name: "Bilbao", country: "Espana" },
  { id: "malaga", slug: "malaga", name: "Malaga", country: "Espana" },
];

const now = new Date().toISOString();

export const coaches: CoachProfile[] = [
  {
    id: "coach-1",
    slug: "cristina-torres-dos-santos",
    name: "Cristina Torres dos Santos",
    headline:
      "Coaching de liderazgo y desarrollo personal en Madrid con sesiones presenciales y online.",
    bio: "Coach profesional con experiencia internacional en liderazgo, equipos y desarrollo ejecutivo. Acompana a profesionales y directivos a ganar claridad, foco y capacidad de decision sin perder el equilibrio personal.",
    categories: ["liderazgo", "ejecutivo", "personal", "confianza-en-si-mismo"],
    citySlug: "madrid",
    cityLabel: "Madrid, Espana",
    country: "Espana",
    sessionModes: ["presencial", "online"],
    languages: ["Espanol", "Ingles", "Portugues", "Frances"],
    basePriceEur: 120,
    pricingDetails: [
      "Sesion inicial de 60 minutos gratuita.",
      "Sesion online de hasta 90 minutos: 120 EUR.",
      "Sesion presencial en Madrid de hasta 90 minutos: 150 EUR.",
    ],
    certifiedStatus: "approved",
    profileStatus: "published",
    visibilityActive: true,
    featured: true,
    heroImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-tima-miroshnichenko-5336951.jpg",
    galleryImageUrls: [
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-fauxels-3184416.jpg",
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-fauxels-3184405.jpg",
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-liza-summer-6382642.jpg",
    ],
    specialties: ["liderazgo", "autoliderazgo", "crecimiento profesional", "confianza"],
    links: {
      whatsapp: "34600111222",
      phone: "+34 600 111 222",
      email: "cristina@example.com",
      web: "https://example.com/cristina",
      linkedin: "https://linkedin.com/in/cristina",
    },
    reviews: [],
    metrics: { totalViews: 28, avgViewSeconds: 28, clicks: { whatsapp: 7, email: 5, mensaje: 6, linkedin: 9 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-2",
    slug: "natalia-tabella",
    name: "Natalia Tabella",
    headline: "Coaching personal, emocional y bienestar en Barcelona, presencial y online.",
    bio: "Trabajo con personas que quieren recuperar energia, mejorar habitos y sostener cambios realistas con seguimiento. Mi enfoque combina claridad, accion y cuidado emocional.",
    categories: ["personal", "bienestar", "emocional", "mujeres-emprendedoras"],
    citySlug: "barcelona",
    cityLabel: "Barcelona, Espana",
    country: "Espana",
    sessionModes: ["presencial", "online"],
    languages: ["Espanol", "Catalan", "Ingles"],
    basePriceEur: 100,
    pricingDetails: ["Sesion individual de 60-75 min: 100 EUR.", "Pack de 4 sesiones disponible."],
    certifiedStatus: "approved",
    profileStatus: "published",
    visibilityActive: true,
    featured: true,
    heroImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-shkrabaanthony-5244025.jpg",
    galleryImageUrls: ["https://encuentratucoach.es/wp-content/uploads/2024/05/portrait-square-07.jpg"],
    specialties: ["habitos", "bienestar", "disciplina", "seguridad personal"],
    links: {
      whatsapp: "34600333444",
      email: "natalia@example.com",
      instagram: "https://instagram.com/natalia",
    },
    reviews: [
      {
        id: "rev-1",
        authorName: "Laura Serrano",
        authorRole: "Clienta",
        rating: 5,
        body: "En pocas sesiones tuve claridad y un plan realista que pude mantener.",
        createdAt: now,
        coachDecision: "approved",
      },
    ],
    metrics: { totalViews: 76, avgViewSeconds: 61, clicks: { whatsapp: 11, email: 4, instagram: 7, mensaje: 8 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-3",
    slug: "javier-molina",
    name: "Javier Molina",
    headline: "Coaching de carrera y confianza en si mismo en Valencia, formato online.",
    bio: "Ayudo a profesionales en transicion laboral a definir su siguiente paso, preparar entrevistas y recuperar confianza para moverse con mas criterio.",
    categories: ["carrera", "confianza-en-si-mismo"],
    citySlug: "valencia",
    cityLabel: "Valencia, Espana",
    country: "Espana",
    sessionModes: ["online"],
    languages: ["Espanol", "Ingles"],
    basePriceEur: 95,
    pricingDetails: ["Sesion online de 75 min: 95 EUR.", "Programa de transicion de 6 sesiones."],
    certifiedStatus: "pending",
    profileStatus: "published",
    visibilityActive: true,
    featured: false,
    heroImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2024/05/pexels-linkedin-2182970-e1715522386290.jpg",
    galleryImageUrls: [],
    specialties: ["cambio profesional", "entrevistas", "claridad"],
    links: { email: "javier@example.com", web: "https://example.com/javier", linkedin: "https://linkedin.com/in/javier" },
    reviews: [
      {
        id: "rev-2",
        authorName: "Marta Rios",
        rating: 4,
        body: "Me ayudo a definir prioridades y preparar entrevistas.",
        createdAt: now,
        coachDecision: "approved",
      },
    ],
    metrics: { totalViews: 48, avgViewSeconds: 53, clicks: { email: 6, web: 3, linkedin: 5, mensaje: 2 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-4",
    slug: "david-gomez",
    name: "David Gomez",
    headline: "Coaching ejecutivo y liderazgo en Bilbao, presencial y online.",
    bio: "Acompano a managers y equipos en comunicacion, foco y rendimiento, con experiencia en pymes y startups que necesitan ordenar decisiones y mejorar ejecucion.",
    categories: ["liderazgo", "ejecutivo"],
    citySlug: "bilbao",
    cityLabel: "Bilbao, Espana",
    country: "Espana",
    sessionModes: ["presencial", "online"],
    languages: ["Espanol"],
    basePriceEur: 140,
    pricingDetails: ["Sesion ejecutiva de 90 min: 140 EUR."],
    certifiedStatus: "approved",
    profileStatus: "published",
    visibilityActive: true,
    featured: false,
    heroImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2024/05/pexels-chloekalaartist-1043474-e1715543775565.jpg",
    galleryImageUrls: [],
    specialties: ["liderazgo", "equipos", "comunicacion"],
    links: { whatsapp: "34600777888", email: "david@example.com" },
    reviews: [],
    metrics: { totalViews: 32, avgViewSeconds: 44, clicks: { whatsapp: 3, email: 2, mensaje: 1 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-5",
    slug: "marta-rios",
    name: "Marta Rios",
    headline: "Coaching personal, emocional y bioemocional en Malaga, formato online.",
    bio: "Trabajo procesos de autoestima, regulacion emocional y habitos sostenibles con un enfoque cercano y practico para que el cambio no se quede en teoria.",
    categories: ["personal", "bioemocional", "emocional"],
    citySlug: "malaga",
    cityLabel: "Malaga, Espana",
    country: "Espana",
    sessionModes: ["online"],
    languages: ["Espanol"],
    basePriceEur: 85,
    pricingDetails: ["Sesion individual de 60 min: 85 EUR.", "Bono mensual con seguimiento."],
    certifiedStatus: "none",
    profileStatus: "published",
    visibilityActive: true,
    featured: false,
    heroImageUrl: "https://encuentratucoach.es/wp-content/uploads/2024/05/portrait-square-11.jpg",
    galleryImageUrls: [],
    specialties: ["autoestima", "emociones", "habitos"],
    links: { whatsapp: "34600000001", email: "marta@example.com" },
    reviews: [],
    metrics: { totalViews: 19, avgViewSeconds: 37, clicks: { whatsapp: 2, email: 2, mensaje: 1 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-6",
    slug: "laura-serrano",
    name: "Laura Serrano",
    headline: "Coaching de pareja y bienestar en Sevilla, formato presencial.",
    bio: "Especialista en comunicacion de pareja, limites y acuerdos con objetivos claros y seguimiento. Tambien trabajo bienestar relacional y decision compartida.",
    categories: ["pareja", "bienestar"],
    citySlug: "sevilla",
    cityLabel: "Sevilla, Espana",
    country: "Espana",
    sessionModes: ["presencial"],
    languages: ["Espanol"],
    basePriceEur: 110,
    pricingDetails: ["Sesion de pareja de 90 min: 110 EUR.", "Sesiones individuales de apoyo disponibles."],
    certifiedStatus: "approved",
    profileStatus: "published",
    visibilityActive: true,
    featured: false,
    heroImageUrl: "https://encuentratucoach.es/wp-content/uploads/2024/05/portrait-square-05.jpg",
    galleryImageUrls: [],
    specialties: ["pareja", "comunicacion", "acuerdos"],
    links: { phone: "+34 611 223 344", email: "laura@example.com", web: "https://example.com/laura" },
    reviews: [],
    metrics: { totalViews: 24, avgViewSeconds: 42, clicks: { phone: 4, email: 1, web: 2, mensaje: 1 } },
    createdAt: now,
    updatedAt: now,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "post-1",
    slug: "cuanto-cuesta-una-sesion-de-coaching-en-espana",
    title: "Cuanto cuesta una sesion de coaching en Espana",
    excerpt: "Guia de precios por especialidad, formato y experiencia del coach.",
    category: "Precios",
    coverImageUrl: "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-fauxels-3184416.jpg",
    publishedAt: now,
    readingMinutes: 8,
    contentHtml:
      "<p>Los rangos habituales se situan entre 60 EUR y 150 EUR por sesion individual, segun especialidad y experiencia.</p><p>El coaching ejecutivo suele situarse en la parte alta del rango.</p>",
    seoTitle: "Precio del coaching en Espana: guia actualizada",
    seoDescription: "Conoce cuanto cuesta una sesion de coaching en Espana segun tipo y modalidad.",
  },
  {
    id: "post-2",
    slug: "como-elegir-un-coach-sin-perder-tiempo",
    title: "Como elegir un coach sin perder tiempo",
    excerpt: "Checklist practica para definir objetivo, modalidad y encaje.",
    category: "Guias",
    coverImageUrl: "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-liza-summer-6382642.jpg",
    publishedAt: now,
    readingMinutes: 6,
    contentHtml:
      "<p>Empieza por tu objetivo en una frase. Luego compara 2 o 3 perfiles por especialidad, modalidad y resenas.</p>",
  },
  {
    id: "post-3",
    slug: "coaching-online-vs-presencial-diferencias",
    title: "Coaching online vs presencial: diferencias reales",
    excerpt: "Ventajas, limites y cuando te conviene cada formato.",
    category: "Comparativas",
    coverImageUrl: "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-shkrabaanthony-5244025.jpg",
    publishedAt: now,
    readingMinutes: 7,
    contentHtml:
      "<p>El online aporta flexibilidad y acceso a mas perfiles. El presencial puede encajar mejor si valoras la cercania.</p>",
  },
  {
    id: "post-4",
    slug: "que-es-el-coaching-y-para-que-sirve-guia-clara-con-ejemplos-reales",
    title: "Que es el coaching y para que sirve: guia clara con ejemplos reales",
    excerpt: "Una guia para entender cuando el coaching tiene sentido y como elegir profesional sin perder tiempo.",
    category: "Guias",
    coverImageUrl: "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-liza-summer-6382642.jpg",
    publishedAt: now,
    readingMinutes: 9,
    contentHtml:
      "<p>El coaching es un proceso de acompanamiento orientado a objetivos, claridad y accion. No sustituye terapia ni consultoria, pero puede acelerar decisiones y foco si el encaje es bueno.</p><p>La clave esta en definir objetivo, contexto, modalidad y expectativas realistas antes de empezar.</p>",
    seoTitle: "Que es el coaching y para que sirve: guia clara con ejemplos reales",
    seoDescription: "Guia clara para entender que es el coaching, cuando tiene sentido y como elegir coach.",
  },
  {
    id: "post-5",
    slug: "coaching-de-liderazgo-habilidades-clave-y-ejercicios-practicos-para-liderar-mejo",
    title: "Coaching de liderazgo: habilidades clave y ejercicios practicos para liderar mejor",
    excerpt: "Ideas aplicables para mejorar comunicacion, foco y toma de decisiones en equipos.",
    category: "Liderazgo",
    coverImageUrl: "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-fauxels-3184405.jpg",
    publishedAt: now,
    readingMinutes: 8,
    contentHtml:
      "<p>El coaching de liderazgo ayuda a ordenar prioridades, mejorar conversaciones dificiles y sostener decisiones con mas criterio.</p><p>El trabajo practico suele centrarse en feedback, delegacion, reuniones y foco.</p>",
    seoTitle: "Coaching de liderazgo: habilidades clave y ejercicios practicos",
    seoDescription: "Habilidades de liderazgo, ejercicios practicos y cuando conviene trabajar con un coach.",
  },
  {
    id: "post-6",
    slug: "el-poder-del-coaching-en-espana",
    title: "El poder del coaching en Espana",
    excerpt: "Panorama de demanda, formatos y como elegir una primera sesion con criterio.",
    category: "Panorama",
    coverImageUrl: "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-fauxels-3184416.jpg",
    publishedAt: now,
    readingMinutes: 7,
    contentHtml:
      "<p>La demanda de coaching en Espana se reparte entre procesos personales, carrera y liderazgo. La diferencia real la marca el encaje entre objetivo, modalidad y profesional.</p>",
    seoTitle: "El poder del coaching en Espana",
    seoDescription: "Panorama del coaching en Espana y claves para elegir mejor.",
  },
  {
    id: "post-7",
    slug: "el-camino-hacia-el-exito-personal-con-coaching-en-espana",
    title: "El camino hacia el exito personal con coaching en Espana",
    excerpt: "Como usar el coaching personal para pasar de bloqueo a accion con pasos concretos.",
    category: "Personal",
    coverImageUrl: "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-shkrabaanthony-5244025.jpg",
    publishedAt: now,
    readingMinutes: 8,
    contentHtml:
      "<p>Cuando el objetivo esta claro y el proceso tiene seguimiento, el coaching personal puede ayudar a sostener cambios que de otra forma se quedan en intencion.</p>",
    seoTitle: "Exito personal con coaching en Espana",
    seoDescription: "Guia para usar coaching personal con objetivos reales y mejor seguimiento.",
  },
  {
    id: "post-8",
    slug: "coaching-en-espana-potencia-crecimiento",
    title: "Coaching en Espana: potencia tu crecimiento",
    excerpt: "Que mirar al comparar coaches y como convertir una primera llamada en una mejor decision.",
    category: "Guias",
    coverImageUrl: "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-tima-miroshnichenko-5336951.jpg",
    publishedAt: now,
    readingMinutes: 6,
    contentHtml:
      "<p>El crecimiento no depende solo del coach; depende tambien de objetivo, ritmo y capacidad de sostener accion. Comparar bien desde el principio evita sesiones poco utiles.</p>",
    seoTitle: "Coaching en Espana: potencia crecimiento",
    seoDescription: "Como comparar coaches y elegir mejor para crecer con mas claridad.",
  },
];

export const faqItems: FaqItem[] = [
  {
    id: "faq-1",
    question: "Cuanto cuesta una sesion de coaching en Espana?",
    answerHtml:
      "<p>El rango habitual esta entre <strong>60 EUR y 150 EUR</strong> por sesion, con variacion segun especialidad, experiencia y modalidad.</p>",
  },
  {
    id: "faq-2",
    question: "Funciona igual el coaching online que el presencial?",
    answerHtml:
      "<p>En muchos objetivos si. La diferencia principal suele estar en la preferencia y el contexto personal.</p>",
  },
  {
    id: "faq-3",
    question: "Como se si un coach esta certificado?",
    answerHtml:
      "<p>La plataforma muestra un distintivo cuando el coach ha enviado documentacion y ha sido aprobada por el equipo.</p>",
  },
  {
    id: "faq-4",
    question: "Cuanto dura un proceso de coaching?",
    answerHtml:
      "<p>Depende del objetivo. Lo habitual es entre 3 y 12 sesiones en procesos de mejora personal o profesional.</p>",
  },
];
