import type { BlogPost, City, CoachCategory, CoachProfile, FaqItem } from "@/types/domain";

export const coachCategories: CoachCategory[] = [
  {
    id: "personal",
    slug: "personal",
    name: "Coaching personal",
    shortDescription: "Hábitos, claridad, autoestima y objetivos personales.",
    icon: "compass",
  },
  {
    id: "carrera",
    slug: "carrera",
    name: "Coaching de carrera",
    shortDescription: "Cambio profesional, entrevistas y transición laboral.",
    icon: "briefcase",
  },
  {
    id: "liderazgo",
    slug: "liderazgo",
    name: "Coaching de liderazgo",
    shortDescription: "Comunicación, equipos y rendimiento profesional.",
    icon: "users",
  },
  {
    id: "ejecutivo",
    slug: "ejecutivo",
    name: "Coaching ejecutivo",
    shortDescription: "Dirección, estrategia y toma de decisiones.",
    icon: "building",
  },
  {
    id: "pareja",
    slug: "pareja",
    name: "Coaching de pareja",
    shortDescription: "Comunicación, acuerdos y objetivos compartidos.",
    icon: "heart",
  },
  {
    id: "bioemocional",
    slug: "bioemocional",
    name: "Coaching bioemocional",
    shortDescription: "Gestión emocional y procesos de cambio profundos.",
    icon: "sparkles",
  },
];

export const cities: City[] = [
  { id: "madrid", slug: "madrid", name: "Madrid", country: "España" },
  { id: "barcelona", slug: "barcelona", name: "Barcelona", country: "España" },
  { id: "valencia", slug: "valencia", name: "Valencia", country: "España" },
  { id: "sevilla", slug: "sevilla", name: "Sevilla", country: "España" },
  { id: "bilbao", slug: "bilbao", name: "Bilbao", country: "España" },
  { id: "malaga", slug: "malaga", name: "Málaga", country: "España" },
];

const now = new Date().toISOString();

export const coaches: CoachProfile[] = [
  {
    id: "coach-1",
    slug: "cristina-torres-dos-santos",
    name: "Cristina Torres dos Santos",
    headline:
      "Coaching de Liderazgo · en Madrid, España · con sesiones presencial y online · Español, inglés, portugués, francés",
    bio: "Coach profesional con experiencia internacional en liderazgo, equipos y desarrollo ejecutivo. Acompaña a profesionales y directivos a ganar claridad, foco y capacidad de decisión.",
    categories: ["liderazgo", "ejecutivo"],
    citySlug: "madrid",
    cityLabel: "Madrid, España",
    country: "España",
    sessionModes: ["presencial", "online"],
    languages: ["Español", "Inglés", "Portugués", "Francés"],
    basePriceEur: 120,
    pricingDetails: [
      "Sesión complementaria (inicial) 60 minutos gratuita.",
      "Sesión online hasta 90 minutos 120€.",
      "Sesión presencial (Madrid) hasta 90 minutos 150€.",
    ],
    certifiedStatus: "approved",
    profileStatus: "published",
    visibilityActive: true,
    featured: true,
    heroImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-tima-miroshnichenko-5336951.jpg",
    galleryImageUrls: [
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-fauxels-3184416.jpg",
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-fauxels-3184405.jpg",
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-liza-summer-6382642.jpg",
    ],
    specialties: ["liderazgo", "auto-liderazgo", "crecimiento profesional"],
    links: {
      whatsapp: "34600111222",
      phone: "+34 600 111 222",
      email: "cristina@example.com",
      web: "https://example.com/cristina",
      linkedin: "https://linkedin.com/in/cristina",
    },
    reviews: [],
    metrics: { totalViews: 28, avgViewSeconds: 28, clicks: { whatsapp: 7, email: 5, mensaje: 6, linkedin: 9 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-2",
    slug: "natalia-tabella",
    name: "Natalia Tabella",
    headline: "Coaching personal y bienestar · Barcelona · presencial y online",
    bio: "Trabajo con personas que quieren recuperar energía, mejorar hábitos y sostener cambios realistas con seguimiento.",
    categories: ["personal"],
    citySlug: "barcelona",
    cityLabel: "Barcelona, España",
    country: "España",
    sessionModes: ["presencial", "online"],
    languages: ["Español", "Catalán", "Inglés"],
    basePriceEur: 100,
    pricingDetails: ["Sesión individual 60-75 min: 100€.", "Pack de 4 sesiones disponible."],
    certifiedStatus: "approved",
    profileStatus: "published",
    visibilityActive: true,
    featured: true,
    heroImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-shkrabaanthony-5244025.jpg",
    galleryImageUrls: ["https://encuentratucoach.es/wp-content/uploads/2024/05/portrait-square-07.jpg"],
    specialties: ["hábitos", "bienestar", "disciplina"],
    links: {
      whatsapp: "34600333444",
      email: "natalia@example.com",
      instagram: "https://instagram.com/natalia",
    },
    reviews: [
      {
        id: "rev-1",
        authorName: "Laura Serrano",
        authorRole: "Clienta",
        rating: 5,
        body: "En pocas sesiones tuve claridad y un plan realista que pude mantener.",
        createdAt: now,
        coachDecision: "approved",
      },
    ],
    metrics: { totalViews: 76, avgViewSeconds: 61, clicks: { whatsapp: 11, email: 4, instagram: 7, mensaje: 8 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-3",
    slug: "javier-molina",
    name: "Javier Molina",
    headline: "Coaching de carrera · Valencia · online",
    bio: "Ayudo a profesionales en transición laboral a definir su siguiente paso, entrevistas y posicionamiento.",
    categories: ["carrera"],
    citySlug: "valencia",
    cityLabel: "Valencia, España",
    country: "España",
    sessionModes: ["online"],
    languages: ["Español", "Inglés"],
    basePriceEur: 95,
    pricingDetails: ["Sesión online 75 min: 95€.", "Programa de transición 6 sesiones."],
    certifiedStatus: "pending",
    profileStatus: "published",
    visibilityActive: true,
    featured: false,
    heroImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2024/05/pexels-linkedin-2182970-e1715522386290.jpg",
    galleryImageUrls: [],
    specialties: ["cambio profesional", "entrevistas", "claridad"],
    links: { email: "javier@example.com", web: "https://example.com/javier", linkedin: "https://linkedin.com/in/javier" },
    reviews: [
      {
        id: "rev-2",
        authorName: "Marta Ríos",
        rating: 4,
        body: "Me ayudó a definir prioridades y preparar entrevistas.",
        createdAt: now,
        coachDecision: "approved",
      },
    ],
    metrics: { totalViews: 48, avgViewSeconds: 53, clicks: { email: 6, web: 3, linkedin: 5, mensaje: 2 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-4",
    slug: "david-gomez",
    name: "David Gómez",
    headline: "Coaching ejecutivo y liderazgo · Bilbao · presencial y online",
    bio: "Acompaño a managers y equipos en comunicación, foco y rendimiento, con experiencia en pymes y startups.",
    categories: ["liderazgo", "ejecutivo"],
    citySlug: "bilbao",
    cityLabel: "Bilbao, España",
    country: "España",
    sessionModes: ["presencial", "online"],
    languages: ["Español"],
    basePriceEur: 140,
    pricingDetails: ["Sesión ejecutiva 90 min: 140€."],
    certifiedStatus: "approved",
    profileStatus: "published",
    visibilityActive: true,
    featured: false,
    heroImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2024/05/pexels-chloekalaartist-1043474-e1715543775565.jpg",
    galleryImageUrls: [],
    specialties: ["liderazgo", "equipos", "comunicación"],
    links: { whatsapp: "34600777888", email: "david@example.com" },
    reviews: [],
    metrics: { totalViews: 32, avgViewSeconds: 44, clicks: { whatsapp: 3, email: 2, mensaje: 1 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-5",
    slug: "marta-rios",
    name: "Marta Ríos",
    headline: "Coaching personal y bioemocional · Málaga · online",
    bio: "Procesos de autoestima, regulación emocional y hábitos sostenibles con enfoque cercano y práctico.",
    categories: ["personal", "bioemocional"],
    citySlug: "malaga",
    cityLabel: "Málaga, España",
    country: "España",
    sessionModes: ["online"],
    languages: ["Español"],
    basePriceEur: 85,
    pricingDetails: ["Sesión individual 60 min: 85€.", "Bono mensual con seguimiento."],
    certifiedStatus: "none",
    profileStatus: "published",
    visibilityActive: true,
    featured: false,
    heroImageUrl: "https://encuentratucoach.es/wp-content/uploads/2024/05/portrait-square-11.jpg",
    galleryImageUrls: [],
    specialties: ["autoestima", "emociones", "hábitos"],
    links: { whatsapp: "34600000001", email: "marta@example.com" },
    reviews: [],
    metrics: { totalViews: 19, avgViewSeconds: 37, clicks: { whatsapp: 2, email: 2, mensaje: 1 } },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "coach-6",
    slug: "laura-serrano",
    name: "Laura Serrano",
    headline: "Coaching de pareja y comunicación · Sevilla · presencial",
    bio: "Especialista en comunicación de pareja, límites y acuerdos con objetivos claros y seguimiento.",
    categories: ["pareja"],
    citySlug: "sevilla",
    cityLabel: "Sevilla, España",
    country: "España",
    sessionModes: ["presencial"],
    languages: ["Español"],
    basePriceEur: 110,
    pricingDetails: ["Sesión de pareja 90 min: 110€.", "Sesiones individuales de apoyo disponibles."],
    certifiedStatus: "approved",
    profileStatus: "published",
    visibilityActive: true,
    featured: false,
    heroImageUrl: "https://encuentratucoach.es/wp-content/uploads/2024/05/portrait-square-05.jpg",
    galleryImageUrls: [],
    specialties: ["pareja", "comunicación", "acuerdos"],
    links: { phone: "+34 611 223 344", email: "laura@example.com", web: "https://example.com/laura" },
    reviews: [],
    metrics: { totalViews: 24, avgViewSeconds: 42, clicks: { phone: 4, email: 1, web: 2, mensaje: 1 } },
    createdAt: now,
    updatedAt: now,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "post-1",
    slug: "cuanto-cuesta-una-sesion-de-coaching-en-espana",
    title: "¿Cuánto cuesta una sesión de coaching en España?",
    excerpt: "Guía de precios por especialidad, formato y experiencia del coach.",
    category: "Precios",
    coverImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-fauxels-3184416.jpg",
    publishedAt: now,
    readingMinutes: 8,
    contentHtml:
      "<p>Los rangos habituales se sitúan entre 60€ y 150€ por sesión individual, según especialidad y experiencia.</p><p>El coaching ejecutivo suele situarse en la parte alta del rango.</p>",
    seoTitle: "Precio del coaching en España: guía actualizada",
    seoDescription: "Conoce cuánto cuesta una sesión de coaching en España según tipo y modalidad.",
  },
  {
    id: "post-2",
    slug: "como-elegir-un-coach-sin-perder-tiempo",
    title: "Cómo elegir un coach sin perder tiempo",
    excerpt: "Checklist práctica para definir objetivo, modalidad y encaje.",
    category: "Guías",
    coverImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-liza-summer-6382642.jpg",
    publishedAt: now,
    readingMinutes: 6,
    contentHtml:
      "<p>Empieza por tu objetivo en una frase. Luego compara 2-3 perfiles por especialidad, modalidad y reseñas.</p>",
  },
  {
    id: "post-3",
    slug: "coaching-online-vs-presencial-diferencias",
    title: "Coaching online vs presencial: diferencias reales",
    excerpt: "Ventajas, límites y cuándo te conviene cada formato.",
    category: "Comparativas",
    coverImageUrl:
      "https://encuentratucoach.es/wp-content/uploads/2026/01/pexels-shkrabaanthony-5244025.jpg",
    publishedAt: now,
    readingMinutes: 7,
    contentHtml:
      "<p>El online aporta flexibilidad y acceso a más perfiles. El presencial puede encajar mejor si valoras la cercanía.</p>",
  },
];

export const faqItems: FaqItem[] = [
  {
    id: "faq-1",
    question: "¿Cuánto cuesta una sesión de coaching en España?",
    answerHtml:
      "<p>El rango habitual está entre <strong>60€ y 150€</strong> por sesión, con variación según especialidad, experiencia y modalidad.</p>",
  },
  {
    id: "faq-2",
    question: "¿Funciona igual el coaching online que el presencial?",
    answerHtml:
      "<p>En muchos objetivos sí. La diferencia principal suele estar en la preferencia y el contexto personal.</p>",
  },
  {
    id: "faq-3",
    question: "¿Cómo sé si un coach está certificado?",
    answerHtml:
      "<p>La plataforma muestra un distintivo cuando el coach ha enviado documentación y ha sido aprobada por el admin.</p>",
  },
  {
    id: "faq-4",
    question: "¿Cuánto dura un proceso de coaching?",
    answerHtml:
      "<p>Depende del objetivo. Lo habitual es entre 3 y 12 sesiones en procesos de mejora personal o profesional.</p>",
  },
];
